import Head from "next/head";
import { useState } from "react";


export default function Layout(props){
    const [navbar, setNavbar] = useState(false)

    function toggle(){
        if(navbar){
            setNavbar(false)
        }else{
            setNavbar(true)
        }
    }

    return(
        <>
            <Head>
                <title>AnimQu | {props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"/>
            </Head>
            <div className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
                <nav className="flex justify-between items-center py-5 px-10 bg-teal-600">
                    <div className="text-2xl sm:text-4xl font-bold">AnimQu</div>
                    <ul className={`sm:p-0 p-4 ${(navbar)? "flex" : "hidden"} sm:flex sm:flex-row flex-col z-50 sm:static absolute top-20 sm:bg-transparent bg-teal-600 right-0 sm:justify-evenly sm:items-center`}>
                        <li className="mx-3 font-bold"><a className="hover:text-teal-200" href="#">Home</a></li>
                        <li className="mx-3 font-bold"><a className="hover:text-teal-200" href="#">About</a></li>
                        <li className="mx-3 font-bold"><a className="hover:text-teal-200" href="#">Donate</a></li>
                    </ul>
                    <i className="fa fa-bars sm:hidden" onClick={toggle}></i>
                </nav>
                <div>
                    {props.children}

                    <footer className="w-full p-5 bg-teal-600 text-center font-bold text-xl mt-6">
                        Dibuat dengan <i className="fa fa-heart"></i> oleh Anonim
                    </footer>
                </div>
            </div>
        </>
    )
}